// <auto-generated />
using System;
using AscomPayPG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AscomPayPG.Migrations.AppLogDB
{
    [DbContext(typeof(AppLogDBContext))]
    [Migration("20240220092119_mail log")]
    partial class maillog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AscomPayPG.Models.DTOs.NotificationLog", b =>
                {
                    b.Property<long>("NlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NlogId"), 1L, 1);

                    b.Property<DateTime?>("DCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DLastTriedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IHasAttachment")
                        .HasColumnType("bit");

                    b.Property<string>("INotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ITryCount")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SAttachmentCount")
                        .HasColumnType("int");

                    b.Property<string>("SCc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRecipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NlogId");

                    b.ToTable("NotificationLog");
                });
#pragma warning restore 612, 618
        }
    }
}
