namespace AscomPayPG.OfflineSecurity.Models
{
    public class OfflineTransactionRequest
    {
        public List<OfflineTransactionSec> OfflineTransactions { get; set; }
        public Key keys { get; set; }
    }
    public class OfflineTransactionSec
    {
        public string TransactionId { get; set; } //ensure uniquness of each transaction
        public string SenderWalletId { get; set; }
        public string ReceiverWalletId { get; set; }
        public bool TransactionStatus { get; set; }
        public decimal TransactionAmount { get; set; }
        public int TransactionType { get; set; }
        public DateTime TransactionDate { get; set; }
        public string Hash { get; set; } // a harshed version of the transaction details
    }

    public class Key
    {
        public Guid userUid { get; set; }
        public string nonce { get; set; } //to ensure uniqueness of each batch, this is also generated by the middle ware during each settlement innitailisation and returned/issued to the mobile app to send during their next transaction reques
        public string BatchSignature { get; set; } //unique signature 
        public string BatchHash { get; set; } //unique signature 
    }
}
